### ISSUE TITLE
test.py 

### ISSUE THREAD

**Issue by ZhenboZhao77** [wangjiangshan0725/GRA#1]
你好作者！
惊艳的作品。请问我在使用obbdet 加载训练好的pth以生成提交dota服务器文件时。
命令如下：
python tools/test.py configs/obb/gra/gra_orcnn_r50fpn1x_ss_dota10.py work_dirs/gra_orcnn_r50fpn1x_ss_dota10/epoch_12.pth  --format-only --options save_dir=work_dirs/Task1_results
报错：
  File "/root/miniconda3/envs/gra/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/cluster/home3/wjs/ARC_2/work_dirs/20240223/feature_best/0.pth'
这个我不是很理解，请问你是如何将训练好的模型生成提交dota服务器文件的？能否告诉我命令

**Comment by wangjiangshan0725** [comment]
Thanks for your interest of our work!

I have fixed this bug and tested the uploaded checkpoint. The result file from the server is shown following.


This is your evaluation result for task 1 (VOC metrics):

mAP: 0.7764905661492079
ap of each class: plane:0.8927444716429493, baseball-diamond:0.817130350591877, bridge:0.5344283388935795, ground-track-field:0.7417945011143975, small-vehicle:0.8001655380375146, large-vehicle:0.8507893716286887, ship:0.8797119790078773, tennis-court:0.9090225049592997, basketball-court:0.8608092235036205, storage-tank:0.8551826283263488, soccer-ball-field:0.6692796614734682, roundabout:0.6837184175817564, harbor:0.7419639579989055, swimming-pool:0.7258090995484014, helicopter:0.6848084479294341
COCO style result:

AP50: 0.7764905661492079
AP75: 0.5177471541202189
mAP: 0.47911114183515524

**Comment by ZhenboZhao77** [comment]
This is your evaluation result for task 1 (VOC metrics):

mAP: 0.7729811481753598
ap of each class: plane:0.894445613124048, baseball-diamond:0.822924247931879, bridge:0.5591369413605813, ground-track-field:0.7626646926576429, small-vehicle:0.7948427318720616, large-vehicle:0.8454712935114892, ship:0.8790736342568315, tennis-court:0.9089547156962888, basketball-court:0.8639445191530691, storage-tank:0.8554468747571369, soccer-ball-field:0.6107083186942799, roundabout:0.6787829433210967, harbor:0.7507742883139668, swimming-pool:0.7117899926880652, helicopter:0.6557564152919612

nice! 很棒的工作！！！
